branches:
        only:
                - develop

shallow_clone: true 

environment:
        BOOST_ROOT: C:\Libraries\boost_1_59_0
        BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0
        INTELOCSDKROOT: C:\Program Files (x86)\Intel\OpenCL SDK\5.3

clone_folder: C:\aura

platform:
        - x64

install:
        - cmd: echo "Downloading conan..."
        - ps: wget http://downloads.conan.io/latest_windows -OutFile conan_installer.exe
        - cmd: conan_installer.exe /VERYSILENT
        - cmd: set PATH=%PATH%;C:\Program Files (x86)\Conan\conan
        - cmd: conan --version

before_build:
        - ps: Start-FileDownload "http://registrationcenter-download.intel.com/akdlm/irc_nas/8386/intel_sdk_for_opencl_2015_r3_x64_setup.msi"
        - start /wait msiexec /i intel_sdk_for_opencl_2015_r3_x64_setup.msi /qn  /l*v msiexec.log

build_script:
        - mkdir build && cd build
        - cmake -DAURA_BASE=OPENCL -DAURA_UNIT_TEST_DEVICE=0 -G"Visual Studio 14 Win64" ..
        - cmake --build . --config Release

test_script:
        - ctest --output-on-failure
